prefix :    <http://example.org/>
prefix dbr: <http://dbpedia.org/resource/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix wd:  <http://www.wikidata.org/entity/>
prefix dcterm: <http://purl.org/dc/terms/>

select ?p ?temp ?official where {
 ?t :hasMeasurement ?x ;
    dcterm:creator ?official .   
 ?x :player ?p ;
    :hasTemperature ?temp .    
}