prefix :    <http://example.org/>
prefix dbr: <http://dbpedia.org/resource/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix wd:  <http://www.wikidata.org/entity/>
prefix dcterm: <http://purl.org/dc/terms/>

select ?p ?item where {
 ?x :player ?p ;
    :wikidataItem ?item
 filter (!regex(str(?item),"http://www.wikidata.org/entity/Q[0-9]+"))
}